// This file is generated by `cargo xtask generate-types`. Do not edit by hand.

export type ProtocolVersion = {
    readonly major: number;
    readonly minor: number;
};

export type ApiResult<T> =
    | {
        readonly tag: "ok";
        readonly value: T;
    }
    | {
        readonly tag: "error";
        readonly error: CalculatorErrorDto;
    };

export type CalculationRequest = {
    readonly parse: ParseSettings;
    readonly semantics: SemanticSettings;
    readonly exactOutput: ExactOutputRequest;
    readonly scientificOutput: ScientificOutputRequest;
    readonly enclosureOutput: EnclosureOutputRequest;
    readonly limits: ResourceLimitRequest;
};

export type ParseSettings = {
    readonly grammar: "default";
    readonly implicitMultiplication: "enabled" | "disabled";
    readonly unicodeAliases: "mathematicalAliases" | "asciiOnly";
    readonly percent: "postfixPercent" | "rejectPercent";
};

export type SemanticSettings = {
    readonly domain: "real";
    readonly angleUnit: "radian" | "degree" | "gradian";
    readonly powerSemantics: "realPrincipal";
};

export type ExactOutputRequest =
    | {
        readonly tag: "omit";
    }
    | {
        readonly tag: "include";
        readonly format: ExactFormatPreference;
    };

export type ExactFormatPreference =
    | "auto"
    | "rational"
    | "finiteDecimal"
    | "mixedFraction"
    | "symbolic";

export type ScientificOutputRequest =
    | {
        readonly tag: "omit";
    }
    | {
        readonly tag: "include";
        readonly significantDigits: number;
        readonly roundingMode: DecimalRoundingMode;
    };

export type DecimalRoundingMode =
    | "nearestTiesToEven"
    | "nearestTiesAwayFromZero"
    | "towardPositiveInfinity"
    | "towardNegativeInfinity"
    | "towardZero"
    | "awayFromZero";

export type EnclosureOutputRequest =
    | {
        readonly tag: "omit";
    }
    | {
        readonly tag: "include";
        readonly format: EnclosureFormat;
    };

export type EnclosureFormat = "exactDyadic";

export type ResourceLimitRequest =
    | {
        readonly tag: "default";
    }
    | {
        readonly tag: "custom";
        readonly value: ResourceLimits;
    };

export type ResourceLimits = {
    readonly maxInputBytes: number;
    readonly maxSourceAstNodes: number;
    readonly maxSourceDepth: number;
    readonly maxExpressionNodes: number;
    readonly maxIntegerBits: number;
    readonly maxCyclotomicOrder: number;
    readonly maxAlgebraicDegree: number;
    readonly maxPolynomialCoefficientBits: number;
    readonly maxResultantDegree: number;
    readonly maxFactorizationWork: number;
    readonly maxRootIsolationSteps: number;
    readonly maxRewriteSteps: number;
    readonly maxPrecisionBits: number;
    readonly maxRefinementRounds: number;
    readonly maxLogicalWorkUnits: string;
    readonly maxPresentationNodes: number;
    readonly maxOutputBytes: number;
};

export type CalculationOutcome =
    | {
        readonly tag: "complete";
        readonly calculation: Calculation;
    }
    | {
        readonly tag: "partial";
        readonly calculation: Calculation;
        readonly reason: IncompleteReason;
        readonly certifiedEnclosure: CertifiedIntervalPresentation;
    };

export type Calculation = {
    readonly exact: ExactOutput;
    readonly scientific: ScientificOutput;
    readonly enclosure: EnclosureOutput;
    readonly metadata: CalculationMetadata;
};

export type ExactOutput =
    | {
        readonly tag: "omitted";
    }
    | {
        readonly tag: "included";
        readonly value: ExactPresentation;
    };

export type ScientificOutput =
    | {
        readonly tag: "omitted";
    }
    | {
        readonly tag: "included";
        readonly value: ScientificPresentation;
    }
    | {
        readonly tag: "unavailable";
        readonly value: UnavailableScientificOutput;
    };

export type EnclosureOutput =
    | {
        readonly tag: "omitted";
    }
    | {
        readonly tag: "included";
        readonly value: CertifiedIntervalPresentation;
    };

export type ExactPresentation = {
    readonly relation: ResultRelation;
    readonly representation: ExactRepresentationKind;
    readonly presentation: PresentationNodeDto;
    readonly plainText: string;
};

export type ScientificPresentation = {
    readonly relation: ResultRelation;
    readonly significand: string;
    readonly exponentTen: string;
    readonly requestedSignificantDigits: number;
    readonly confirmedSignificantDigits: number;
    readonly roundingMode: DecimalRoundingMode;
    readonly presentation: PresentationNodeDto;
};

export type UnavailableScientificOutput = {
    readonly requestedSignificantDigits: number;
    readonly confirmedSignificantDigits: number;
    readonly roundingMode: DecimalRoundingMode;
    readonly reason: IncompleteReason;
};

export type CertifiedIntervalPresentation = {
    readonly relation: ResultRelation;
    readonly lower: ExactDyadic;
    readonly upper: ExactDyadic;
    readonly format: EnclosureFormat;
    readonly presentation: PresentationNodeDto;
};

export type ExactDyadic = {
    readonly coefficient: string;
    readonly exponentTwo: string;
};

export type CalculationMetadata = {
    readonly exactRepresentation: ExactRepresentationKind;
    readonly simplificationStatus: SimplificationStatus;
    readonly semanticSettings: SemanticSettings;
    readonly methods: readonly MethodTag[];
    readonly internalPrecisionBits: number;
    readonly refinementRounds: number;
    readonly confirmedSignificantDigits: number;
    readonly assurance: AssuranceLevel;
    readonly protocolVersion: ProtocolVersion;
};

export type IncompleteReason =
    | {
        readonly tag: "precisionLimit";
        readonly requestedDigits: number;
        readonly confirmedDigits: number;
    }
    | {
        readonly tag: "computationLimit";
        readonly kind: ComputationLimitCode;
    };

export type SimplificationStatus =
    | {
        readonly tag: "fullySimplifiedWithinLimits";
    }
    | {
        readonly tag: "partiallySimplified";
        readonly reason: IncompleteReason;
    };

export type PresentationNodeDto =
    | {
        readonly tag: "text";
        readonly text: string;
    }
    | {
        readonly tag: "row";
        readonly children: readonly PresentationNodeDto[];
    }
    | {
        readonly tag: "fraction";
        readonly numerator: PresentationNodeDto;
        readonly denominator: PresentationNodeDto;
    }
    | {
        readonly tag: "superscript";
        readonly base: PresentationNodeDto;
        readonly exponent: PresentationNodeDto;
    }
    | {
        readonly tag: "radical";
        readonly index: RadicalIndexDto;
        readonly radicand: PresentationNodeDto;
    }
    | {
        readonly tag: "function";
        readonly name: FunctionNameDto;
        readonly argument: PresentationNodeDto;
    }
    | {
        readonly tag: "parenthesized";
        readonly value: PresentationNodeDto;
    };

export type RadicalIndexDto =
    | {
        readonly tag: "square";
    }
    | {
        readonly tag: "nth";
        readonly value: string;
    };

export type FunctionNameDto =
    | "sin"
    | "cos"
    | "tan"
    | "asin"
    | "acos"
    | "atan"
    | "sqrt"
    | "exp"
    | "log";

export type ResultRelation = "exactEqual" | "approximatelyEqual" | "elementOf";

export type ExactRepresentationKind =
    | "integer"
    | "rational"
    | "finiteDecimal"
    | "rationalPiMultiple"
    | "radical"
    | "realAlgebraic"
    | "generalSymbolic";

export type MethodTag =
    | "rationalReduction"
    | "radicalExtraction"
    | "specialAngle"
    | "cyclotomicReduction"
    | "algebraicMinimalPolynomial"
    | "algebraicRootIsolation"
    | "symbolicRetention"
    | "certifiedIntervalEvaluation"
    | "adaptivePrecisionRefinement";

export type AssuranceLevel = "exact" | "certifiedEnclosure";

export type InputActionDto =
    | {
        readonly tag: "digit";
        readonly value: number;
    }
    | {
        readonly tag: "decimalPoint";
    }
    | {
        readonly tag: "constant";
        readonly value: ConstantDto;
    }
    | {
        readonly tag: "function";
        readonly value: FunctionDto;
    }
    | {
        readonly tag: "binaryOperator";
        readonly value: BinaryOperatorDto;
    }
    | {
        readonly tag: "percent";
    }
    | {
        readonly tag: "openParenthesis";
    }
    | {
        readonly tag: "closeParenthesis";
    }
    | {
        readonly tag: "deleteBackward";
    }
    | {
        readonly tag: "clearEntry";
    }
    | {
        readonly tag: "clearAll";
    }
    | {
        readonly tag: "memoryClear";
    }
    | {
        readonly tag: "memoryRecall";
    }
    | {
        readonly tag: "memoryAdd";
    }
    | {
        readonly tag: "memorySubtract";
    }
    | {
        readonly tag: "evaluate";
    };

export type InputPolicyDto = {
    readonly calculationRequest: CalculationRequest;
    readonly percentPolicy: PercentPolicyDto;
};

export type PercentPolicyDto =
    | "expressionPercent"
    | "calculatorPercent";

export type SessionDispatchResult =
    | {
        readonly tag: "state";
        readonly state: SessionStateDto;
    }
    | {
        readonly tag: "calculate";
        readonly state: SessionStateDto;
        readonly source: string;
        readonly request: CalculationRequest;
    }
    | {
        readonly tag: "inputError";
        readonly state: SessionStateDto;
        readonly error: InputErrorDto;
    };

export type SessionStateDto = {
    readonly source: string;
    readonly cursorUtf16: number;
    readonly selectionUtf16: OptionalTextSpanDto;
    readonly hasAns: boolean;
    readonly hasMemory: boolean;
    readonly display: SessionDisplayDto;
};

export type SessionDisplayDto =
    | {
        readonly tag: "editing";
    }
    | {
        readonly tag: "result";
        readonly calculation: Calculation;
    }
    | {
        readonly tag: "error";
        readonly error: CalculatorErrorDto;
    }
    | {
        readonly tag: "calculating";
    };

export type InputErrorDto = {
    readonly code: InputErrorCodeDto;
};

export type InputErrorCodeDto =
    | "invalidDigit"
    | "invalidCursor"
    | "selectionOutOfBounds"
    | "actionNotAllowedAfterError"
    | "memoryEmpty";

export type ConstantDto =
    | "pi"
    | "e"
    | "ans"
    | "memory";

export type FunctionDto = FunctionNameDto;

export type BinaryOperatorDto =
    | "add"
    | "subtract"
    | "multiply"
    | "divide"
    | "power";

export type CalculatorErrorDto =
    | {
        readonly tag: "parse";
        readonly code: ParseErrorCode;
        readonly span: TextSpanDto;
        readonly expected: readonly ExpectedTokenDto[];
    }
    | {
        readonly tag: "domain";
        readonly code: DomainErrorCode;
        readonly span: OptionalTextSpanDto;
    }
    | {
        readonly tag: "inputLimit";
        readonly code: InputLimitErrorCode;
    }
    | {
        readonly tag: "computationLimit";
        readonly code: ComputationLimitCode;
    }
    | {
        readonly tag: "unsupportedFeature";
        readonly code: UnsupportedFeatureCode;
    }
    | {
        readonly tag: "internalInvariant";
        readonly code: InternalInvariantCode;
    }
    | {
        readonly tag: "unsupportedProtocol";
        readonly code: UnsupportedProtocolCode;
    };

export type TextSpanDto = {
    readonly start: number;
    readonly end: number;
};

export type OptionalTextSpanDto =
    | {
        readonly tag: "none";
    }
    | {
        readonly tag: "some";
        readonly value: TextSpanDto;
    };

export type ExpectedTokenDto = {
    readonly kind: ExpectedTokenKindDto;
};

export type ExpectedTokenKindDto =
    | "number"
    | "identifier"
    | "operator"
    | "openParenthesis"
    | "closeParenthesis"
    | "endOfInput";

export type ParseErrorCode =
    | "unexpectedToken"
    | "unexpectedEnd"
    | "unknownIdentifier"
    | "invalidNumberLiteral"
    | "missingFunctionParenthesis"
    | "implicitMultiplicationDisabled"
    | "percentRejected";

export type DomainErrorCode =
    | "divisionByZero"
    | "logarithmOfNonPositive"
    | "evenRootOfNegative"
    | "inverseTrigonometricOutOfRange"
    | "tangentPole"
    | "zeroToNegativePower"
    | "indeterminateZeroToZero"
    | "nonRealPower";

export type InputLimitErrorCode =
    | "inputTooLong"
    | "sourceAstTooDeep"
    | "sourceAstTooLarge"
    | "expressionTooLarge"
    | "integerTooLarge"
    | "outputTooLarge"
    | "invalidSignificantDigits"
    | "invalidResourceLimit";

export type ComputationLimitCode =
    | "algebraicDegree"
    | "polynomialCoefficientBits"
    | "resultantDegree"
    | "factorizationWork"
    | "rootIsolationSteps"
    | "rewriteSteps"
    | "precisionBits"
    | "refinementRounds"
    | "logicalWorkUnits"
    | "presentationNodes";

export type UnsupportedFeatureCode =
    | "complexDomain"
    | "portableProofCertificate"
    | "evaluationEngine"
    | "constantEvaluation"
    | "functionEvaluation"
    | "nonIntegerPower";

export type InternalInvariantCode =
    | "nonCanonicalRational"
    | "invalidAlgebraicIsolation"
    | "invalidCertifiedInterval"
    | "nonDeterministicCacheAccounting"
    | "presentationWithoutEvaluation"
    | "invalidParsedNumberLiteral";

export type UnsupportedProtocolCode =
    | "unknownTag"
    | "unknownCode"
    | "unsupportedMajorVersion";
